// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/teacher-home/FeedCentered.tsx": () => import("../components/mockups/teacher-home/FeedCentered.tsx"),
  "./components/mockups/teacher-home/ListMode.tsx": () => import("../components/mockups/teacher-home/ListMode.tsx"),
  "./components/mockups/teacher-home/StatFirst.tsx": () => import("../components/mockups/teacher-home/StatFirst.tsx")
};
