// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/parent-home/ChildPortraitCard.tsx": () => import("../components/mockups/parent-home/ChildPortraitCard.tsx"),
  "./components/mockups/parent-home/DayStoryTimeline.tsx": () => import("../components/mockups/parent-home/DayStoryTimeline.tsx"),
  "./components/mockups/parent-home/FamilyCommandCenter.tsx": () => import("../components/mockups/parent-home/FamilyCommandCenter.tsx"),
  "./components/mockups/parent-home/MilestoneTracker.tsx": () => import("../components/mockups/parent-home/MilestoneTracker.tsx"),
  "./components/mockups/teacher-home-v2/AgendaMode.tsx": () => import("../components/mockups/teacher-home-v2/AgendaMode.tsx"),
  "./components/mockups/teacher-home-v2/CommandPalette.tsx": () => import("../components/mockups/teacher-home-v2/CommandPalette.tsx"),
  "./components/mockups/teacher-home-v2/InsightsDashboard.tsx": () => import("../components/mockups/teacher-home-v2/InsightsDashboard.tsx"),
  "./components/mockups/teacher-home-v2/StudentRosterFirst.tsx": () => import("../components/mockups/teacher-home-v2/StudentRosterFirst.tsx"),
  "./components/mockups/teacher-home-v3/ActionInbox.tsx": () => import("../components/mockups/teacher-home-v3/ActionInbox.tsx"),
  "./components/mockups/teacher-home-v3/OceanMetaphor.tsx": () => import("../components/mockups/teacher-home-v3/OceanMetaphor.tsx"),
  "./components/mockups/teacher-home-v3/SplitPanel.tsx": () => import("../components/mockups/teacher-home-v3/SplitPanel.tsx"),
  "./components/mockups/teacher-home-v3/StorybookSummary.tsx": () => import("../components/mockups/teacher-home-v3/StorybookSummary.tsx"),
  "./components/mockups/teacher-home/FeedCentered.tsx": () => import("../components/mockups/teacher-home/FeedCentered.tsx"),
  "./components/mockups/teacher-home/ListMode.tsx": () => import("../components/mockups/teacher-home/ListMode.tsx"),
  "./components/mockups/teacher-home/StatFirst.tsx": () => import("../components/mockups/teacher-home/StatFirst.tsx")
};
